name: module3_task3
on:
  push:
  schedule:
    - cron: "30 22 * * *"
jobs:
  module3_task3:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module3_task3 && ./setup.sh
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make unit-tests
      - run: cd module3_task3 && make integration-tests
      - run: cd module3_task3 && make validate
      - run: cd module3_task3 && make help
      - run: cd module3_task3 && make lint
      - run: cd module3_task3 && make package
      - uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: ./module3_task3/awesome-website.zip
