name: module3_task3
on:
  push:
  schedule:
    - cron: "30 22 * * *"
jobs:
  module3_task3:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module3_task3 && ./setup.sh
      - run: cd module3_task3 && make build
      - run: cd module3_task3 && make unit-tests
      - run: cd module3_task3 && make integration-tests
      - run: cd module3_task3 && make validate
      - run: cd module3_task3 && make help
      - run: cd module3_task3 && make lint
      - run: cd module3_task3 && make package
      - uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: ./module3_task3/awesome-website.zip
    build-releas:
    permissions:
      contents: write
    needs: build-artifact
    if: startsWith(github.ref, 'refs/tags/1.0.0')
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download awesome-website.zip file
        uses: actions/download-artifact@v3
        with:
          name: awesome-website
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awesome-website.zip
          body: ./module3_task3/DEPLOY.md
