name: module3_task1
on:
  push:
  schedule:
    - cron: "30 22 * * *"
jobs:
  module3_task1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module3_task1 && make build
